### ISSUE TITLE
Error running pelican-asf to build apache/www-site

### ISSUE THREAD

**Issue by rotty3000** [apache/infrastructure-pelican#29]
I just forked this repo then followed the first steps in DOCKER.md which built fine.

I then ran `docker run -it -p8000:8000 -v $PWD:/site pelican-asf` from the root of my fork of `apache/www-site`.

In return I got:
```
TOOLS: /tmp/pelican-asf/bin
Building web site with: ('/bin/bash', '-c', '(pelican content --settings ./pelican.auto.py --o site-generated -r -l -b 0.0.0.0)')
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 5, in <module>
    from pelican.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/pelican/__init__.py", line 19, in <module>
    from pelican.generators import (ArticlesGenerator,  # noqa: I100
  File "/usr/local/lib/python3.9/site-packages/pelican/generators.py", line 14, in <module>
    from pelican.cache import FileStampDataCacher
  File "/usr/local/lib/python3.9/site-packages/pelican/cache.py", line 6, in <module>
    from pelican.utils import mkdir_p
  File "/usr/local/lib/python3.9/site-packages/pelican/utils.py", line 21, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)
Traceback (most recent call last):
  File "/tmp/pelican-asf/bin/buildsite.py", line 383, in <module>
    main()
  File "/tmp/pelican-asf/bin/buildsite.py", line 379, in main
    args.func(args)
  File "/tmp/pelican-asf/bin/buildsite.py", line 230, in build_dir
    subprocess.run(buildcmd, cwd=auto_dir, check=True, env=env)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/bin/bash', '-c', '(pelican content --settings ./pelican.auto.py --o site-generated -r -l -b 0.0.0.0)')' returned non-zero exit status 1.
```

**Comment by gstein** [comment]
For: @dave2wave and @bdelacretaz

**Comment by dave2wave** [comment]
@rotty3000 I've tested the current status. Please rebuild your docker file from the latest and make the workaround noted in #31 then everything should work.

**Comment by rotty3000** [comment]
Got it, thank you. I'm try on the weekend 🙂
